# vi:ft=yaml:fdl=0:fdm=expr:fde=v\:lnum<11?0\:(getline(v\:lnum)=~'^\\s*$'&&getline(v\:lnum+1)=~'\\S'?'<1'\:1):
#
#     ░░░░░  ░░       ░░░░░   ░░░░░░ ░░░░░░  ░░ ░░░░░░░░ ░░░░░░░░ ░░    ░░ ░░    ░░ ░░░    ░░░ ░░
#    ▒▒   ▒▒ ▒▒      ▒▒   ▒▒ ▒▒      ▒▒   ▒▒ ▒▒    ▒▒       ▒▒     ▒▒  ▒▒   ▒▒  ▒▒  ▒▒▒▒  ▒▒▒▒ ▒▒
#    ▓▓▓▓▓▓▓ ▓▓      ▓▓▓▓▓▓▓ ▓▓      ▓▓▓▓▓▓  ▓▓    ▓▓       ▓▓      ▓▓▓▓     ▓▓▓▓   ▓▓ ▓▓▓▓ ▓▓ ▓▓
#    ██   ██ ██      ██   ██ ██      ██   ██ ██    ██       ██       ██       ██    ██  ██  ██ ██
# ██ ██   ██ ███████ ██   ██  ██████ ██   ██ ██    ██       ██       ██ ██    ██    ██      ██ ███████
#
# @author: thiagoalessio <thiagoalessio@me.com>
# @url: https://github.com/thiagoalessio/dotfiles

env:
  TERM: xterm-256color

window:
  padding:
    x: 1
    y: 1
  decorations: none
  startup_mode: Maximized

font:
  size: 12.0
  normal:
    family: terminus
    style: Regular
  bold:
    family: terminus
    style: Regular

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

background_opacity: 0.82

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

shell:
  program: /bin/bash
  args:
    - --login

draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: N,        mods: Control|Shift, action: SpawnNewInstance }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Add,      mods: Control,       action: IncreaseFontSize }
  - { key: Subtract, mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
